

CREATE TABLE APP_USER (
	username VARCHAR (50) PRIMARY KEY,
	pass VARCHAR (30) NOT NULL
);

CREATE TABLE QUIZ(
	quiz_title VARCHAR (250) PRIMARY KEY
);

CREATE TABLE QUESTION(
    question_id VARCHAR (500) PRIMARY KEY,
	quiz_title VARCHAR(250) NOT NULL,
	FOREIGN KEY (quiz_title) REFERENCES QUIZ(quiz_title)
);

CREATE TABLE ANSWER(
	answer_text VARCHAR(200) PRIMARY KEY,
	correct NUMBER NOT NULL,
	question_id VARCHAR (500) NOT NULL,
	FOREIGN KEY (question_id) REFERENCES QUESTION(question_id)
);

CREATE TABLE INFORMATION(
	title VARCHAR(100) NOT NULL PRIMARY KEY,
	text_path VARCHAR(50) NOT NULL,
	images_path VARCHAR(50) NOT NULL
);
